name: Auto Tag on PR Merge

on:
  pull_request:
    branches:
      - main
    types: [closed] 

jobs:
  tag_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 
      - name: Extract Tag from PR Body
        id: extract_tag
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          # Use grep with a regex pattern to find the tag (e.g., [tag:v1.0.0])
          TAG=$(echo "$PR_BODY" | grep -oP '\[tag:\K[^\]]+')
          
          if [ -z "$TAG" ]; then
            echo "::notice title=Skipping Tagging::No [tag:vX.Y.Z] found in the PR description. Skipping tag creation."
            echo "tag_name=" >> $GITHUB_OUTPUT
          else
            echo "Found tag command: [tag:$TAG]"
            echo "tag_name=$TAG" >> $GITHUB_OUTPUT
          fi
      - name: Create Git Tag and Push
        if: steps.extract_tag.outputs.tag_name != '' # Only run if a tag was found
        run: |
          TAG_NAME="${{ steps.extract_tag.outputs.tag_name }}"
          echo "Creating Git tag: $TAG_NAME"
          
          # Create the tag locally on the merged commit
          git tag $TAG_NAME
          
          # Push the new tag to GitHub
          git push origin $TAG_NAME
          
          echo "Successfully tagged commit with $TAG_NAME"
