name: Terraform Apply

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  pull-requests: write # Required to post comments
      
jobs:
  terraform:
    name: Terrafom 
    runs-on: ubuntu-latest 
    env:
      GITHUB_TOKEN: ${{ github.token }}
      AWS_ROLE: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ECR_OIDC
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VERSION: ${{ vars.TF_VERSION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform Init
        id: init
        run: |
          terraform init -lock=false -input=false 
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -lock=false -input=false -out=tfplan
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -input=false -auto-approve tfplan