name: Terraform Plan

on:
  push:
    branches:
      - dev
      - uat
      - prod

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
      
jobs:
  code_scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  start-runner:
    timeout-minutes: 5
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    permissions:
      actions: write
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/ECR_OIDC
          aws-region: ${{ vars.AWS_REGION }}
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-123
          ec2-instance-type: t3.nano
          subnet-id: subnet-123
          security-group-id: sg-123
          iam-role-name: my-role-name # optional, requires additional permissions
          aws-resource-tags: > # optional, requires additional permissions
            [
              {"Key": "Name", "Value": "ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
            ]

  terraform:
    name: Terrafom 
    needs: start-runner 
    runs-on: ${{ needs.start-runner.outputs.label }} 
    env:
      TF_VAR_AWSROLE: 
    steps:
      - name: Checkout Repo
        run: actions/checkout@v4
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-iam-role: ${{secrets.AWS_ROLE }}
          aws-region: us-east-1
      - name: Terraform Commands
        run: |
          $terraform fmt
          terraform init 

  stop-runner:
    timeout-minutes: 2
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner 
      - terraform
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}